### ISSUE TITLE
Toolbar Icon appears very small

### ISSUE THREAD

**Issue by rgleason** [nohal/dashboardsk_pi#32]
**Describe the bug**
The plugin loads and I see a very small Puzzle icon in the toolbar.
When I click on it nothing happens. 
I believe this is because I do not have a SK signal.

**Desktop (please complete the following information if applicable):**
 - OS: Win 11
 - Version 571 very current.

![DashboardSK](https://user-images.githubusercontent.com/2363959/225484990-e0f791e3-17c6-4325-a508-4ef0ab4562e8.png)

**Comment by nohal** [comment]
Can't reproduce the icon problem.

The plugin won't show anything until you configure it to do so, please read the manual and configure some dashboard in the preferences.

**Comment by rgleason** [comment]
There is no manual that I am aware of.  This occurs on high resolution displays. I have shown what happens. It does exist.
Bdbcat fixed it. Search on DPI aware under issues.

**Comment by nohal** [comment]
https://opencpn-manuals.github.io/main/dashboardsk/index.html

Under issues where?

**Comment by nohal** [comment]
And search for what exactly?

**Comment by rgleason** [comment]
There is no manual that I am aware of.  Found it https://opencpn-manuals.github.io/main/dashboardsk/index.html   They need to have better links. 

This occurs on high resolution displays. I have shown what happens. It does exist.
Bdbcat fixed it. Search on DPI aware under issues.

**Comment by rgleason** [comment]
OK I will try to configure.

**Comment by nohal** [comment]
If you don't have SignalK data feed, you may either use the NSK plugin (https://opencpn-manuals.github.io/main/nsk/index.html) or connect to the data feed on `signalk.stupan.se` on port `3000`
