### ISSUE TITLE
Manual How to Connect to 

### ISSUE THREAD

**Issue by rgleason** [nohal/dashboardsk_pi#33]
> If you don't have SignalK data feed, you may either use the NSK plugin (https://opencpn-manuals.github.io/main/nsk/index.html) or connect to the data feed on signalk.stupan.se on port 3000

Found http://stupan.se   there is no connection to signalk_stupan.se and norton security says it is dangerous due to not having a certificate.

Since I can seem to get nsk going it would be great to have some signalK stream to work with. 

How would I make this connection?  In Opencpn Connnections?
A screenshot of your connection might help.

I think it would be very helpful to have this instruction for a signalK stream at the end of the manual.

**Comment by nohal** [comment]
<img width="761" alt="Screen Shot 2023-03-16 at 12 38 41 PM" src="https://user-images.githubusercontent.com/249856/225670413-88861ee5-944c-41b5-b771-1a223a8fa29f.png">

**Comment by rgleason** [comment]
Thanks, not finished yet. 

Connection to signalk.stupen.se

![DBsk-1](https://user-images.githubusercontent.com/2363959/225684581-ca0468b3-7279-49d3-b7a7-ec1c1ac0d6b5.png)

 I could not find "Depth" so I used  vessels "SOG"  It would be nice to have  selection of "vessel" or "aton"  then a "search" feature 

![DBsk-2](https://user-images.githubusercontent.com/2363959/225684645-ab139b1c-dd57-412e-81aa-243917b2bb47.png)

Voyage progressing

![DBs-3](https://user-images.githubusercontent.com/2363959/225684707-b6ee1be3-f233-4289-90f0-d451ec7dd018.png)

Larger scale.

![DBsk-4](https://user-images.githubusercontent.com/2363959/225684851-ac427850-06be-4461-98fc-534409fba362.png)

So there must be a depth somewhere.

**Comment by nohal** [comment]
You seem to be missing all the icons. Not reproducible here.
Are you sure the key you selected is actually providing the data? The MMSI certainly is not the one of the "own ship" in the data feed you are using.
