### ISSUE TITLE
Adjustment of color swatches in Prefs

### ISSUE THREAD

**Issue by rgleason** [nohal/dashboardsk_pi#34]
I think these are a little bit larger than necessary.
![dashboardsk-A](https://user-images.githubusercontent.com/2363959/225670596-d5584aec-ddee-46fd-9b18-bd7d5f216c87.png)

**Comment by rgleason** [comment]
Well someday it will get fixed.  I leave it for you to close as I  am not closing it.  Don't know why the main icon is not showing, but that is some bug or missing icon, I think.

**Comment by rgleason** [comment]
PS  Very nice dashboard features!  Thanks so much!

**Comment by rgleason** [comment]
BTW These are the recommended win11 settings for high res displays, so it is not an "unnormal" display and it will need to be handled properly sometime.

**Comment by nohal** [comment]
The wxWidgets bug https://github.com/wxWidgets/wxWidgets/pull/24456 is fixed in 3.2.5
