### ISSUE TITLE
wrong adress  in "web site" button

### ISSUE THREAD

**Issue by filochard** [nohal/dashboardsk_pi#42]
Hi Pavel
I'm testing dashboardsk inside flatpak 
I found a little problem here : 
![dashboard](https://github.com/nohal/dashboardsk_pi/assets/16304019/f2f56b38-00f9-4fb7-9b7d-5303a13984b1)
The "web site" button leads to a 404 error
(NB for NSK this button is OK and leads to https://opencpn.org/OpenCPN/plugins/nsk.html  )

**Comment by nohal** [comment]
The opencpn.org website is currently being reorganized, I still don't have the new URL.

**Comment by nohal** [comment]
Turns out to be just a change in casing of the file name
