### ISSUE TITLE
Sample config not copied on first start after installation

### ISSUE THREAD

**Issue by filochard** [nohal/dashboardsk_pi#43]
Hi Pavel
I'm testing dashboardsk  inside flatpat

It isn't easy to find the sample_config.json file when you click on "preferences" button : 
![dashboard](https://github.com/nohal/dashboardsk_pi/assets/16304019/9b13c782-8b90-4656-b582-ea20f2725be8)

this leads to : 
![dashboardsk2](https://github.com/nohal/dashboardsk_pi/assets/16304019/3a7864c4-cc5c-426c-826a-fb2a22a8fa9c)

clicking on the "import" button opens a file manager where you need to  right the mouse to display hidden files... : 
![dashboardsk3](https://github.com/nohal/dashboardsk_pi/assets/16304019/599faa93-ab50-4d47-b006-097b577e4744)

Then you have to travel through the tree (knowing where to go) and find the file with a long path : 
![dashboardsk4](https://github.com/nohal/dashboardsk_pi/assets/16304019/8a8cff9c-4b68-4a8b-87b8-c7152f95e246)

After that at last you finally get have what you want in the right upper side of OpenCPN  : 
![dashboardsk5](https://github.com/nohal/dashboardsk_pi/assets/16304019/e62f5590-f7c6-42c1-8e60-d08fe6b7f70a)

PS
Besides testing inside flatpak
 I finally succeed to create a rpm for linux distribution and tested it
I installed the rpm 
it appears in the plugin list as installed
I can activate it and can use the "preference"  button leading to the same problem to find the sample_config.json file and import it
at last I get the same display as for flatpak 

creating the rpm need some ricks but it is possible and it works the same way as the plugin works inside flatpak

**Comment by nohal** [comment]
That file is never intended to be touched manually.

On a **new** install, when **no configuration exists**, it is used to create a few sample instruments to show "something" to the user. See https://github.com/nohal/dashboardsk_pi/blob/main/src/dashboardsk_pi.cpp#L159-L164

**Comment by nohal** [comment]
It is an example of things that need to be patched by downstream packagers like you to actually do what they are designed to do in case the packaging does not follow the design patterns.

**Comment by filochard** [comment]
It's not only a downstream packager problem

What I meant is : 
**Inside flatpak** the new install doesn' t automatically use the sample_config.json file 
"preference" button leads to this empty window


![dashboardsk6](https://github.com/nohal/dashboardsk_pi/assets/16304019/4a70e275-14e3-4732-8d2a-6014d5d1f30d)


you have to look for sample_config.json  and import it to get this : 

![dashboardsk7](https://github.com/nohal/dashboardsk_pi/assets/16304019/de79cb88-3d75-4834-87a9-8c0b05727749)

Something is going wrong inside the flatpak installation of this plugin

**Comment by nohal** [comment]
You do never have to look for that file as a user.

Do a test:
- Stop the flatpak
- Execute `rm ~/.var/app/org.opencpn.OpenCPN/data/opencpn/plugins/DashboardSK_pi/data/config.json`
- Start the flatpak.

This is the only moment when that sample config should be used. If it is not, than that is an error that needs to be fixed.

**Comment by filochard** [comment]
I already 

> You do never have to look for that file as a user.
> 
> Do a test:
> 
>     * Stop the flatpak
> 
>     * Execute `rm ~/.var/app/org.opencpn.OpenCPN/data/opencpn/plugins/DashboardSK_pi/data/config.json`
> 
>     * Start the flatpak.
> 
> 
> This is the only moment when that sample config should be used. If it is not, than that is an error that needs to be fixed.

I already did this when testing before opening this issue ! 
No change at all

**Comment by filochard** [comment]
Ok : the title is more correct ;-)
