### ISSUE TITLE
Right click menu to open preferences

### ISSUE THREAD

**Issue by Hakansv** [nohal/dashboardsk_pi#58]
Low prio: "Nice to have"
Compare inbound Dashboard. Using right click on a instrument panel the preferences are easy reachable.
The "long" way by Options->Plugins->DashboardSK->Preferences is sometime inconvenient.

**Comment by nohal** [comment]
This will be covered in #17 where the mouse event handling interface will be added to the instruments.
Similar to what is already implemented for the newly added pager control in  https://github.com/nohal/dashboardsk_pi/commit/18aab3070fd7cc7b69cf52a6c56f913a3511c517

**Comment by Hakansv** [comment]
Very good. I obviously didn't read back all about this plugin, 
So we don't need a second issue about the same thing.
