### ISSUE TITLE
Can’t move windows with touch screen

### ISSUE THREAD

**Issue by Ray22113** [nohal/dashboardsk_pi#59]
**Describe the bug**
I am unable to move the dashboard windows with the touchscreen. I have tried with touchscreen interface turned in and off. It seems like with titlebar may be too small?

mall other plugin windows I’ve tried such as watchdog, weather routing, grib, etc work with the touchscreen. 

**To Reproduce**
Open a dashboard window on the screen and try to move it with a touchscreen monitor. 

**Expected behavior**
I would expect to be able to drag and relocate the window and resize. 

**Desktop (please complete the following information if applicable):**

Debian 12.2

**Comment by nohal** [comment]
The only window this plugin has are the preferences. Is that what you can't move? The dashboard instruments are rendered directly to the chart canvas and always docked to an edge of the screen with configurable offsets and spacing, but besides that. they are not movable on the screen by design.

**Comment by Ray22113** [comment]
Damn, wrong plugin!  The SK plugin is working perfectly!

**Comment by Ray22113** [comment]
Yeah, that's the one I'm talking about.  It's a bummer because we use the tactics plugin and also like the ASW/S TWA/S graph that they use.

**Comment by nohal** [comment]
I will be adding similar functionality in this plugin in the future, but there is still some ground work to be done first an days have only 24 hours :)
