### ISSUE TITLE
path problem for the config files

### ISSUE THREAD

**Issue by filochard** [nohal/dashboardsk_pi#66]
Hi Pavel
(and Happy New Year)

I have tested Dashboardsk installed inside flatpak  (and with legacy rpm install allowed with some patches)

I discovered a little problem in the flatpak installation
The readonly data are stored in a right place
/home/myusername/.var/app/org.opencpn.OpenCPN/data/opencpn/plugins/DashboardSK_pi/data

BUT nothing has been created in the path where are stored the writeable files (where other plugins store what they have created)
/home/myusername/.var/app/org.opencpn.OpenCPN/config/opencpn/plugins/
Inside it we should find a created directory : 
/home/myusername/.var/app/org.opencpn.OpenCPN/config/opencpn/plugins/DashboardSK/ and inside it a copy of config.json and perhaps of sample_config.json from the 
/home/myusername/.var/app/org.opencpn.OpenCPN/data/opencpn/plugins/DashboardSK_pi/data

That's inside /home/myusername/.var/app/org.opencpn.OpenCPN/config/opencpn/plugins/DashboardSK/  that  config.json may be modified ! not in the /home/myusername/.var/app/org.opencpn.OpenCPN/data/opencpn/plugins/DashboardSK_pi/data

as examples watchdog stores its config here:
/home/philippe/.var/app/org.opencpn.OpenCPN/config/opencpn/plugins/watchdog/WatchdogConfiguration.xml

and logbookkonni its written text files here : 
/home/myusername/.var/app/org.opencpn.OpenCPN/config/opencpn/plugins/logbook/data/*.txt 
besides the layouts extracted from a zip which is inside
/home/myusername/.var/app/org.opencpn.OpenCPN/data/opencpn/plugins/LogBookKonni_pi/data/Layouts.zip

NB the same  problem already occurred for watchdog see : 
https://github.com/rgleason/watchdog_pi/issues/20

NB Alec gave some explanations here : 
https://github.com/OpenCPN/OpenCPN/issues/2312

Hope this will help

Best Regards

**Comment by nohal** [comment]
I probably got lost. What exactly does not work?

**Comment by filochard** [comment]
What I meant is that there are 2 different paths in a flatpak installation
one for the readonly data
/home/myusername/.var/app/org.opencpn.OpenCPN/**data**/opencpn/plugins/
one for the written files
/home/myusername/.var/app/org.opencpn.OpenCPN/**config**/opencpn/plugins/

DashboardSK works as it is but the place for  config.json modified by the user should be in the **config** path, not in the **data** path

That's what Alec talked about : 
https://github.com/OpenCPN/OpenCPN/issues/2312

**Comment by nohal** [comment]
> That's what Alec talked about : [OpenCPN/OpenCPN#2312](https://github.com/OpenCPN/OpenCPN/issues/2312)

I see him saying that he opened that issue just by accident and he was wrong, no mention of these paths.

What real problem will be fixed if I move the `config.json` file?

**Comment by filochard** [comment]
I suppose that if DashboardSK is updated, the config.json file inside
/home/myusername/.var/app/org.opencpn.OpenCPN/**data**/opencpn/plugins/DashboardSK_pi/data
will be overwritten by this update
And all the settings done by the user will be lost

That wouldn't be the case if config.json is inside
/home/myusername/.var/app/org.opencpn.OpenCPN/**config**/opencpn/plugins/DashboardSK/ : 
the first use of  DashboardSK should create a first copy of config.json there, it would be modified by the user, but should remain there out of reach of ulterior updates of the plugin 

In a legacy install, there's a great difference between the pieces of a program are installed and read-only
and the files that can be modified or added by an user 

I thought it was necessary to create such a difference inside flatpak :
/home/myusername/.var/app/org.opencpn.OpenCPN/**data**/  being for the program  component
(like /usr/lib /usr/share for linux)
/home/myusername/.var/app/org.opencpn.OpenCPN/**config**/ being for the config or added files 
(like /home/username/  for linux)

Flatpak is supposed to be a sandbox inside a linux system  simulating the organization of a linux system : 
programs in one path, read-only
user's files in an other path, writable and not polluting the program

But maybe I am wrong

**Comment by nohal** [comment]
So if you update DashboardSK in flatpak you lose your configuration data in your environment? Does not seem to be the case for me and I honestly don't see a codepath that would lead to such a behavior.

Or do you see some problem in the legacy installation scenario?

**Comment by filochard** [comment]
I am testing OpenCPN both in Flatpak and with a legacy install (some patches allow me to still do  a legacy installation)

I have just activated DashboardSK inside Flatpak, and can't say if an update will erase config.json

But in the legacy install  there's no config.json at all
neither inside /usr/share/opencpn/plugins/DashboardSK_pi/data/
nor inside /home/myname/.opencpn/plugins/ where the other plugins store the user's data or config files 

Since config.json seems supposed to be created in the program data path for flatpak 
that can't be done in a read-only directory of the linux system (/usr/share subdirectories are read only for a simple user) 

I'm looking for a workaround for a legacy installation

**Comment by nohal** [comment]
OK, so this issue has nothing to do with flatpak and is about the legacy install you do for Mageia?

**Comment by filochard** [comment]
yes i discovered it with a legacy install

But I wondered if this would imply some problems inside flatpak when I saw that for flapak the config.json is in the **data** directory and not in the **config** directory like the config files or written files of the other programs

Just have a look at the trees of
 /home/yourname/.var/app/org.opencpn.OpenCPN/config/*
 /home/yourname/.var/app/org.opencpn.OpenCPN/data/*

**Comment by nohal** [comment]
No, it is absolutely no problem for flatpak or installation via the plugin manager. That is why I keep asking what real issue we talk about.

**Comment by filochard** [comment]
Thanks a lot Pavel
you did the trick for a legacy install ;-) 
Now it works perfectly
there just a little cosmetic detail that doesn't prevent it to work
config.json is here : 
/home/myname/.opencpn/DashboardSK_pi/
instead of : 
/home/myname/.opencpn/plugins/DashboardSK_pi/
nevertheless it works 
and the config.json can be modified and used after modification

Best Regards

**Comment by filochard** [comment]
to correct the config path,
I just applied a patch to add one 322 line in /src/dashboardsk_pi.cpp	: 
       + wxFileName::GetPathSeparator() + "plugins" 

here is the patch : 
--- /src/dashboardsk_pi.cpp	2024-01-02 22:31:07.000000000 +0100
+++ /src/dashboardsk_pi.cpp	2024-01-03 00:32:33.628145722 +0100
@@ -319,6 +319,7 @@
 wxString dashboardsk_pi::GetConfigDir()
 {
     wxString cfgPath = *GetpPrivateApplicationDataLocation()
+        + wxFileName::GetPathSeparator() + "plugins" 
         + wxFileName::GetPathSeparator() + "DashboardSK_pi"
         + wxFileName::GetPathSeparator();
     if (!wxDirExists(cfgPath))


Now the config.json is inside
/home/myname/.opencpn/plugins/DashboardSK_pi/
and may be used correctly
The sample_config.json is used to create the first config.json 
It works as well as with your commit, but the path is more correct since  it's now besides the other plugins

I keep my patch until you apply this little modification in a next commit

Best Regards
Philippe

**Comment by nohal** [comment]
I do not think I will implement this change upstream as the `plugins` subdirectory is owned by the PIM for it's metadata and cache and I have no intention to prevent it from being completely purged at the user's or PIM's discretion.

**Comment by filochard** [comment]
Sorry for the Mid air crash
your answer happened when I was reediting my previous comment
I keep my patch for our legacy install where I have now side by side : 

/home/myname/.opencpn/plugins/celestial_navigation/
/home/myname/.opencpn/plugins/climatology_pi/
/home/myname/.opencpn/plugins/DashboardSK_pi/
/home/myname/.opencpn/plugins/logbook/
/home/myname/.opencpn/plugins/watchdog/
/home/myname/.opencpn/plugins/weatherfax/
and others
